### ISSUE TITLE
Basic styling disables browser's native word correction

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5-typing#100]
## Steps to reproduce
1. Type a word with a mistake, for example "testter".
2. Select it and apply bold with CTRL + B.
3. Right click on a word and try to correct it with native browser spell checker.

## Current result
Nothing happens.

## Expected result
Word should change to chosen one.

## Other informations
OS: Windows 10, Ubuntu 16.04
Release: 0.10.0

**Comment by Reinmar** [comment]
That's a browser issue. We can't do anything about it.

**Comment by Reinmar** [comment]
Sorry, I haven't read the issue precisely. I thought that it's about `<b>wu</b>rd` not being underlined by a browser, which would be "can't fix".

![image](https://user-images.githubusercontent.com/156149/27536348-fe8cd9ca-5a6e-11e7-94f9-34cbbef11b95.png)

But as for not being able to correct a word such as in this:

![image](https://user-images.githubusercontent.com/156149/27536364-127c73dc-5a6f-11e7-9b3e-e15d31eeb7ec.png)

it's a valid issue and it's actually pretty serious.

**Comment by Reinmar** [comment]
Errr... this is pretty bad (on Chrome at least).

So, let's say we have:

```html
<p>This is <strong>buold</strong></p>
```

You try to correct the "buold" word. The browser tries to change the DOM to:

```html
<p>This is <b>bold</b></p>
```

Yep, `<strong>` gets replaced with `<b>`.

In general – browser replaces the entire element, not just the text node.

**Comment by Reinmar** [comment]
Firefox is better here – it replaces "buold" text node with the proper "build" text node. So this change we are able to handle.

**Comment by Reinmar** [comment]
Safari does the same as Chrome.

**Comment by Reinmar** [comment]
Some idea could be to convert all the new children proposed in the mutation to model and compare stuff there. And once we'll figure out that this is just a text change, we can replace the original fragment with this (even with a brute force replace of the entire element content).

Another idea could be to do the same kind of diffing in the view still but we'd need to convert the content to model anyway because finding the position at which the text changed in the model would otherwise be really hard.

**Comment by Reinmar** [comment]
Anyway, this is something about 2-3 days of work. Optimistically.

**Comment by szymonkups** [comment]
Related issue https://github.com/ckeditor/ckeditor5/issues/491, similar situation happens there: when user starts typing in:
```html
<p><a href=""><i>Link{}</i></a></p>
```
It is changed to:
```html
<p><i><a href="">Link</a></i></p> 
```

**Comment by Reinmar** [comment]
And the letter is inserted outside `<a>`, right? `<p><i><a href="">Link</a>x</i></p> `

**Comment by szymonkups** [comment]
> And the letter is inserted outside `<a>`, right? `<p><i><a href="">Link</a>x</i></p>`

Yes - updated my previous comment.
