### ISSUE TITLE
Input feature should not modify document when InputCommand is disabled

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-typing#107]
When selection is non-collapsed and input command is disabled then typing removes text in the selection.

**Comment by Reinmar** [comment]
See https://github.com/ckeditor/ckeditor5-typing/commit/f935d66df8bede1b8f49edda73cebe1e07a26466#diff-8052e4286a369903aa5d7f6c2d8b7190R73 for rationale.
