### ISSUE TITLE
Forward delete removes empty paragraph when delete command is disabled

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-typing#109]
- An empty paragraph has to be just before an image.
- Command has to be executed by <kbd>Delete</kbd> key press.

---

![jul-13-2017 11-57-32 2](https://user-images.githubusercontent.com/1057056/28161153-b774be16-67c2-11e7-9795-649a24d482d0.gif)

**Comment by Reinmar** [comment]
This is not a problem with the command (as you demonstrated on the GIF :D) but a problem with keystroke listener in the widget plugin. Please open a ticket in ckeditor5-widget for it.

**Comment by Reinmar** [comment]
Actually, I'll open the ticket in ckeditor5-widget.

**Comment by oskarwrobel** [comment]
I know that keystroke is a problem but I didn't know how delete plugin uses this keystroke.

**Comment by Reinmar** [comment]
Done: https://github.com/ckeditor/ckeditor5-widget/issues/6
