### ISSUE TITLE
Backspace in an empty block preceded by another empty block leaves a paragraph

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-typing#113]
https://github.com/ckeditor/ckeditor5-engine/issues/1012 caused a regression. If you have a content like:

```html
<h2></h2>
<h3>^</p>
```

And press backspace, you're left with a paragraph. The expected result is `<h2>^</h2>`.

That's caused by https://github.com/ckeditor/ckeditor5-engine/issues/1012 because backspace in such a case is handled by extending the selection to the left and then doing `deleteContent()`. Unfortunately, at the second step we don't know if the content was fully selected initially or not, so we delete everything.

**Comment by Reinmar** [comment]
We're considering a couple of options:

* make `deleteContent()` handle extending the selection if it's collapsed – thanks to that it'd know its initial state,
* add an option to `deleteContent()` allowing to turn off/on this "leave paragraph if entire content was selected" behaviour,
* move the "handle entire content selection" behaviour to a separate method.

Unfortunately, none of these options sound great.

**Comment by pomek** [comment]
> #106 caused a regression. 
#106 won't be merged (?).

**Comment by Reinmar** [comment]
Sorry, wrong link.

**Comment by Reinmar** [comment]
Engine's part: https://github.com/ckeditor/ckeditor5-engine/issues/1045.
