### ISSUE TITLE
Exception when copy and paste text with attributes to the text with attributes

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-typing#119]
### How to reproduce:

```javascript
<paragraph>fo[o <$text bold="true">b]ar</text></paragraph>
```
then copy and paste

### Result:
```
Uncaught TypeError: Cannot read property 'index' of undefined
    at MutationHandler._handleTextNodeInsertion (input.js:294)
    at MutationHandler.handle (input.js:152)
    at Input._handleMutations (input.js:105)
    at Document.listenTo (input.js:50)
    at Document.fire (emittermixin.js:281)
    at MutationObserver._onMutations (mutationobserver.js:248)
```

![aug-31-2017 08-54-39](https://user-images.githubusercontent.com/1057056/29910413-2c4015be-8e2a-11e7-9cb1-78077204340c.gif)

**Comment by Reinmar** [comment]
I'm not able to reproduce it. Which version of Chrome do you have?

**Comment by oskarwrobel** [comment]
I'm on exactly the same version. ckeditor5 master and all packages are up to date.

**Comment by oskarwrobel** [comment]
It doesn't occur with `ArticlePresets`. It occurs on http://localhost:8125/ckeditor5-basic-styles/tests/manual/basic-styles.html.

**Comment by Reinmar** [comment]
OK, because there's no clipboard plugin.

**Comment by Reinmar** [comment]
I'm going to modify the manual test to avoid such confusion in the future.

**Comment by Reinmar** [comment]
Done in https://github.com/ckeditor/ckeditor5-basic-styles/commit/1dd1c95f4a5703f360af9c9943ae5a6e4f6d1879.
