### ISSUE TITLE
Tests - Spellchecking integration does not work on Edge

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-typing#126]
The main issue: https://github.com/ckeditor/ckeditor5/issues/615

Broken tests in this package:

- [x] Edge 16.16299.0 (Windows 10 0.0.0) Spellchecking integration "after all" hook FAILED

In order to reproduce these issues, please follow this instruction – https://github.com/ckeditor/ckeditor5/issues/615#issuecomment-340414494 – _How to run it on my local machine?_

**Comment by Reinmar** [comment]
BTW, I don't know if this is in anyway related, but there are a couple of tests which use `execCommand()` and I think we should rewrite all of them to get rid of `execCommand()`. The current method leads to problem with focus and hence tests stability. Plus, it's hard to predict what how browsers will react.

So, it's better to just fire mock mutation events and do DOM changes manually like the other tests do.

**Comment by pomek** [comment]
This issue is no longer valid after changes in [engine](https://github.com/ckeditor/ckeditor5-engine/compare/t/1177).

**Comment by Reinmar** [comment]
The link to the change which fixed this issue doesn't work after removing the branch ;) But anyway, we can close this.
