### ISSUE TITLE
[IME] Character inserts twice after typing at the beginning of the word with inline styling

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5-typing#129]
## Steps to reproduce
**Windows**
1. http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Change the keyboard language to `Hiragana`.
3. Put the caret at the beginning of the word with inline style (i.e. `Bold`).
4. Press <kbd>a</kbd> to start the composition.

**OS X**
1. http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Change the keyboard language to `Hiragana`.
3. Put the caret at the beginning of the word with inline style (i.e. `Bold`).
4. Press <kbd>a</kbd> to start the composition.
5. Press <kbd>a</kbd> once again.

## Current result
Character has been inserted twice.

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/34517860-1318848a-f07d-11e7-8e48-c148c88d307f.gif)
 
## Other information
OS: Windows 10, MacOS X
Browser: Chrome, Opera
Release: 1.0.0-alpha2

**Comment by f1ames** [comment]
Tested on MacOS where it behaves similar (with some small differences). Safari (11.0.3 (11604.5.6.1.1)) works as described in the issue.

### Chrome (64.0.3282.167)
First character doesn't start composition and then two characters are inserted after pressing <kbd>a</kbd> once:
![feb-27-2018 14-10-27-chrome](https://user-images.githubusercontent.com/1061942/36730632-61a83246-1bc8-11e8-894c-0f39e8b6e40c.gif)

### Firefox (58.0.2 (64-bit))
First character is inserted starting a composition and then pressing <kbd>a</kbd> multiple times doesn't insert anything (however you can see IME panel is updated after each press). And after some more characters are inserted it shows whole inserted text:
![feb-27-2018 14-11-45-firefox](https://user-images.githubusercontent.com/1061942/36730642-68c09d66-1bc8-11e8-8a8a-ef0fb821e1ba.gif)
