### ISSUE TITLE
Non printable keys like volume up remove the content

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5-typing#136]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open CKEditor 5 instance with typing plugin, e.g. [classic editor demo](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/examples/builds/classic-editor.html).
2. Select some text.
3. Use volume up button.

### Expected result

Text is not removed.

### Actual result

Text is removed.

![nonprintablekeys](https://user-images.githubusercontent.com/5353898/36197117-3444de62-1173-11e8-9d51-0aa09ebcb2e0.gif)

## Other details

Other examples keys like:

* [Menu key](https://en.wikipedia.org/wiki/Menu_key)
* Play/Pause, Rewind (other media buttons)
* Insert Key
* Num lock

---

* Browser: All
* OS: Win10

**Comment by jodator** [comment]
I can confirm the same issue on Linux Mint 18.3 Cinnamon, browsers checked: Chrome & Firefox.

For me the buttons that causes the bug are:
- menu
- home
- scroll lock
- pause/break
- num lock

Buttons that do not cause the bug:
- media buttons (play, volume +/-, mute)
- email
- calculator
- print screen

**Comment by Reinmar** [comment]
We need to hardcode so-called "safe keys", unfortunately. You can find them in https://github.com/ckeditor/ckeditor5-typing/blob/a02eab5f73bf2c0288a7149b34424c1badbc380a/src/input.js#L312-L328 and this list isn't complete yet. Actually, I don't think that it ever will be, but fortunately, it's not a critical problem.

**Comment by Reinmar** [comment]
A DUP with some more keys reported in https://github.com/ckeditor/ckeditor5/issues/955.

**Comment by pomek** [comment]
Referring to https://github.com/ckeditor/ckeditor5/issues/955 - Windows key does not change anything in the editor. It even isn't caught by the observer.

**Comment by Reinmar** [comment]
> Referring to [ckeditor/ckeditor5#955](https://github.com/ckeditor/ckeditor5/issues/955) - Windows key does not change anything in the editor. It even isn't caught by the observer.

Are you sure this is true on all browsers on all platforms?

**Comment by pomek** [comment]
No. I don't remember do I check it on Edge (Win 10).

**Comment by Reinmar** [comment]
Because we can easily add the win key and other keys we know are safe to the "safe keys" object and just be future proof. Assuming anything here would have to be backed by serious proofs. Especially that issue like the one with the win key were already reported.
