### ISSUE TITLE
[Android] Cannot remove or type when image is selected

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5-typing#161]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Latest `master` / `v10.1.0`

## 📋 Steps to reproduce

Related to #130.

1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
1. Select an image.
1. Try to type something.
1. Press <kbd>Backspace</kbd> and try to remove the image.

## ✅ Expected result

It is possible to type over or remove an image with <kbd>Backspace</kbd>.

## ❎ Actual result

Not possible to type over or remove an image with <kbd>Backspace</kbd>.

## 📃 Other details that might be useful

Tested with `Chrome 67` on `Android 8`. See also https://github.com/ckeditor/ckeditor5-typing/issues/130#issuecomment-355027214.

**Comment by f1ames** [comment]
It seems that the fake selection + <kbd>Backspace</kbd> causes some issues:

![android backspace image](https://user-images.githubusercontent.com/1061942/41904174-047aa220-7938-11e8-881d-20e4023673c8.gif)
_Here I'm pressing only <kbd>Backspace</kbd> after image is selected._

![android typing image](https://user-images.githubusercontent.com/1061942/41904177-07c1a8de-7938-11e8-9097-96d1f2dc2acd.gif)
_Here I'm typing ad then pressing <kbd>Backspace</kbd> after image is selected._

**The logged values is native mutations array.**

**Comment by Reinmar** [comment]
TBH, I don't understand what I see :D


Fake selection is non-collapsed so backspacing it should lead to some results – a mutation deleting that selected piece of content. Note, though, that these mutations may be filtered by our mutation observer.

**Comment by f1ames** [comment]
> TBH, I don't understand what I see :D

Yep, the problem is you can record preview with visible console but no keyboard, or record video on a devices with keyboard visible but no console. Haven't found a way yet to capture all this 😞 

> Note, though, that these mutations may be filtered by our mutation observer.

That may be the case, as `mutations` received in the `input._handleMutations()` method are empty.

Anyway, I found that #158 PR may help in this case (here tested on `t/83` branch):

![android image 83](https://user-images.githubusercontent.com/1061942/41906774-168fc6aa-793f-11e8-90cd-7f3c66dedb78.gif)

So typing and backspacing over selected image works. The difference is that selection is placed in a different place than on desktop Chrome.

**Comment by f1ames** [comment]
I have rechecked this issue on Android `6.0.1` and `8.0.0` with latest Chrome (`67`). The #158 PR fixed this issue but there is a problem with selection being placed in an incorrect position.

I am closing this one and will report selection problem in a follow up ticket.
