### ISSUE TITLE
CKE5 sometimes inserts bogus "@" character for empty editables

### ISSUE THREAD

**Issue by dimaip** [ckeditor/ckeditor5-typing#168]
We in Neos CMS got reported this issue https://github.com/neos/neos-ui/issues/2036
Sometimes empty editables get upcasted to `<p>@</p>`.
It happens here: https://github.com/ckeditor/ckeditor5-typing/blob/master/src/utils/injecttypingmutationshandling.js#L150
Any ideas?

**Comment by Reinmar** [comment]
Ouch! @scofalik you were right worrying that it will backfire :D 

@dimaip, do you think that you could create a sample on which we could reproduce it? I see in the ticket on your side that it may be related your custom placeholder.

I also raised https://github.com/ckeditor/ckeditor5/issues/479 to the current iteration because it's a popular request.

**Comment by dimaip** [comment]
@Reinmar I disabled custom placeholder plugin but it's still there.
Honestly I don't know how to reproduce it outside of Neos. For us it happens only on direct properties of document node types (sorry, Neos terminology)... I tried to do a quick debugging but didn't spot any difference to other editables so far. Could spend more time with it this evening.

**Comment by scofalik** [comment]
> Ouch! @scofalik you were right worrying that it will backfire :D

Yup, it must be our hack. However, after a thought I came to a conclusion that it should be safe. 🤷‍♂️ , we need to fix it then.

**Comment by Reinmar** [comment]
Yeah, but unless we're able to reproduce it we may not be able to figure out what happens there. 

In the worst case scenario, we can try to check it in Neos, but it may be hard to debug there and will require far more time.

A couple of questions:

* Does it happen on all browsers?
* Is there some integration/Neos code which may try to append something inside the editor? The code that fails handles mutations so perhaps it's triggered with something odd. That would also explain why you're not able to reproduce it outside Neos.

**Comment by Reinmar** [comment]
And a bonus questions – with what content exactly do you enable the editor? White spaces and stuff may be crucial here.

**Comment by dimaip** [comment]
> unless we're able to reproduce it we may not be able to figure out what happens there.
I understand that quite well :) I could PM you on Slack a read-only login to one of our installations, would that do? If not I'd need more time to dig into it and figure out myself what's wrong. Or there's a docker container....

> Does it happen on all browsers?

At least chrome & FF.

> Is there some integration/Neos code which may try to append something inside the editor?
Don't think so. But man, it's a big system with a lot of stuff going on...

> what content exactly do you enable the editor?
This is the precise content: `<div data-__neos-property="teaser" data-__neos-editable-node-contextpath="/sites/site/a/node-vgqklgw8i7xaf@user-dimaip;language=ru" class="neos-inline-editable" property="typo3:teaser" data-neos-node-type="Sfi.Site:News"></div>`

**Comment by dimaip** [comment]
Duh, sorry about the noise. The issue was caused that on some malformed Neos setups the editables were initialized twice. So at best you could check for double init of CKE on the same dom node, to save noobs like me some debug time in the future. Or just close this issue.
