### ISSUE TITLE
[FF] Editor crashes after pressing space with bold after another space

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-typing#183]
### Steps to reproduce

1. Put the caret after space.
2. Press <kbd>Ctrl+B</kbd>.
3. Press space.

An error is thrown.

This is a regression. The error is thrown in a new function (`findMappedViewAncestor`) but that function is a cut-paste from another place, so it probably would throw anyway. I wonder what changed to make this throw, though.

**Comment by Mgsy** [comment]
Might be related - https://github.com/ckeditor/ckeditor5/issues/720

**Comment by scofalik** [comment]
False alarm - I've checked it on a sample which didn't have the latest CKE5.

**Comment by Reinmar** [comment]
That's a wonderful news :)
