### ISSUE TITLE
Moving the selection should reset the buffer

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-typing#20]
1. open http://tests.ckeditor.dev:1030/build/amd/tests/undo/manual/undo
2. type "aaa" in one place,
3. move selection to another,
4. type "bbb",
5. move selection to another,
6. type "ccc",
7. Undo.

Expected: there should be 3 undo steps.

Actual: there is only one undo step.

Changing the selection should reset the buffer. That's it.

**Comment by Reinmar** [comment]
#21 is another case to cover when fixing this issue.

**Comment by Reinmar** [comment]
This is very tricky, because we need to reset the buffer when selection changes... but not when that change is caused by typing. So the typing feature will need to block change buffer when they operate on the model.

**Comment by Reinmar** [comment]
Let's try this way:

1. We add `ChangeBuffer.lock()` and `unlock()` methods. They should make the change buffer ignore everything that happens around.
2. When the input or delete feature makes it changes, it should lock the buffer, so it isn't reset by those.
3. Change buffer should also listen to `change:attribute` and `change:range` on the selection to reset itself when those things change. But only when it's not locked, ofc.

**Comment by maxbarnas** [comment]
Prototype of fix for #21 seems to help with this issue. In the meanwhile I'll add tests for the ticket.

**Comment by maxbarnas** [comment]
Manual test and early version of integration test was just [commited](https://github.com/ckeditor/ckeditor5-typing/commits/t/20). Also, because this issue is tightly related to #21 , there will be testing of styles (Bold and/or Italic)

 There are obvious deficiencies e.g., lack of `InputCommand`, `Bold` and/or `Italic`. It'll be corrected soon.
