### ISSUE TITLE
Quotes not always are transformed correctly.

### ISSUE THREAD

**Issue by elszczepano** [ckeditor/ckeditor5-typing#205]
Environment: Chrome.
Steps to reproduce:
1. Add empty quotes and then insert content into.
2. Quotes are not transformed properly.

![2019-07-05 10 27 05](https://user-images.githubusercontent.com/23155008/60711022-38a4d680-9f14-11e9-80b9-c1c7762c8147.gif)

**Comment by Reinmar** [comment]
I think that we could solve this by not requiring that there's any text between those quotes. So, to make this transformation apply even when you type `""`.

**Comment by Reinmar** [comment]
If it's as trivial as I think, let's do this in it26. If not, let's ignore this as the ROI is minimal.

**Comment by jodator** [comment]
Yes - the quotes should be replaced only on `""` if you type inside non-converted quotes the transformation shouldn't occur. The same way if you undo transformation and type after it - it should be also not transformed (as it is now).

**Comment by jodator** [comment]
I've just checked this and I'm not able to reproduce it:

![Peek 2019-07-19 12-20](https://user-images.githubusercontent.com/247363/61528674-ab877480-aa1f-11e9-996e-ddf87fdef045.gif)

After typing `""` it is automatically transformed to `“”` as described in @Reinmar's comment.
The typing inside non-transformed `""` is not a bug as transformation should not be fired then.

**Comment by jodator** [comment]
I've added a tests for this case in #200 fix.
