### ISSUE TITLE
Typing's undo step should be broken by applying an attribute

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-typing#21]
1. Open http://tests.ckeditor.dev:1030/build/amd/tests/basic-styles/manual/basic-styles
2. Type few letters (make sure to type in a place where italic isn't applied).
3. Press italic button.
4. Type few more letters.
5. Press undo button.

Only the letters typed in step 4 should be undone.

This issue is very similar to #20. Changing selection attributes should reset a buffer, just like moving the selection should.

**Comment by maxbarnas** [comment]
I noticed, that undo operation deletes just part of the text typed in step 4 above, when typed text is quite long (dozen or more characters).

**Comment by Reinmar** [comment]
That's the expected result. It's so called undo step – https://github.com/ckeditor/ckeditor5-typing/blob/7c446342e8a742b77ab260ad4a7f22d51b58e0b8/src/input.js#L36

**Comment by maxbarnas** [comment]
I kind of suspected this. Thanks for pointing out the actual piece of code responsible for that.

**Comment by maxbarnas** [comment]
Prototype of solution is available in [t/21](https://github.com/ckeditor/ckeditor5-typing/commits/t/21) branch.

Listener of `changesDone` event wraps all the `change:attribute` events to allow proper unlocking `ChangeBuffer`. 

Listening to `change:range` does not affect the fix, nor locking buffer in `ChangeBuffer#_handleKeydown`.

This prototype also fixes problem when changing selection: https://github.com/ckeditor/ckeditor5-typing/issues/20.

**Comment by f1ames** [comment]
Pushed changes to [t/21](https://github.com/ckeditor/ckeditor5-typing/commits/t/21). The only thing missing are unit/integration input tests. Since #48 with `InputCommand` should be ready soon, I am not sure if it makes sense to create missing tests now without it and then rewrite it using `InputCommand`.

**Comment by f1ames** [comment]
Noticed https://github.com/ckeditor/ckeditor5-undo/issues/58.
