### ISSUE TITLE
Introduce a way to check if changes were introduced by typing

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-typing#214]
I think it would be useful to have a way to check if given changes were done through typing. I see it as a method on `Typing` or `InputCommand` instance.

This could be solved in one of two ways:

1. Add special batch type (yeah, we made precedence with undo :P).
2. Store all `InputCommand` batches in some kind of a `WeakSet`.

Then, we could use it like this:

```js
modelDocument.on( 'change', ( evt, batch ) => {
    if ( typingPlugin.isTyping( batch ) ) {
        // ...
    }
} );
```

```js
modelDocument.registerPostFixer( writer => {
    if ( typingPlugin.isTyping( writer.batch ) ) {
        // ...
    }
} );
```

When this is done, we should fix changes introduced by this PR: https://github.com/ckeditor/ckeditor5-typing/pull/213/files

**Comment by Reinmar** [comment]
Sounds really interesting. 👍

**Comment by jodator** [comment]
I'm also in favor of such change. There are many cases in which we need such check and some standardized way for this would be awesome.

I like the `typing` batch type (and possibly create `undo` batch types also).

**Comment by Reinmar** [comment]
> When this is done, we should fix changes introduced by this PR: https://github.com/ckeditor/ckeditor5-typing/pull/213/files

If this PR needs to add some API that we'd be removing after closing this ticket, I'd do that right now.

**Comment by Reinmar** [comment]
> I like the `typing` batch type (and possibly create `undo` batch types also).

I can't tell if this makes sense in a long run – whether we'll not need dozens of types and/or those types will become unreliable for some reason (by getting weaker meaning or something). Once we'll start introducing them there will be no way back.

> 2\. Store all `InputCommand` batches in some kind of a `WeakSet`.

So, unless you're really sure about the new types, I'd go for local changes, like the proposed here.

**Comment by jodator** [comment]
Quick questions about API:

1. Shouldn't we check `isInput()` vs `isTyping()` - technically we would like to check user input as in `Input` plugin.
2. Resolving the `isInput()` vs `isTyping()` will resolve where the method lands. For me it looks like `inputPlugin.isInput( batch )` - other wise as proposed by @scofalik.
3. Should we expose the `InputCommand.batches`? I'd say this is `protected` but OTOH the `InputCommand.buffer` is exposed.

**Comment by Reinmar** [comment]
Ad 1. Typing = input + delete. So we can even have multiple methods for that in multiple places.

Ad 3. What would be the purpose of exposing it?

**Comment by jodator** [comment]
> Ad 3. What would be the purpose of exposing it?

None probably. I'd leave that as private.

**Comment by scofalik** [comment]
Probably not worth exposing right now. I use input buffer batches in track changes (and AFAIR they are used somewhere else too) but that's the "current batch" and this is an important property. Old batches, stored in a `WeakMap` are probably not useful.
