### ISSUE TITLE
[Safari, iOS?] Error is thrown after native spell checking popup is used

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-typing#26]
See http://giphy.com/gifs/3oEjI9qZIWjFsRToEo

I'm able to reproduce the same without deleting the content so it's not related to https://github.com/ckeditor/ckeditor5-engine/issues/520.

Note: Not every combination of letters causes this error, so to reproduce this consistently:
1. Create new paragraph.
2. Type "sdf".
3. Choose "pdf" that appears.

Reproduced on Safari 9.1.

**Comment by Reinmar** [comment]
Before we start working on this let's check what's the severity of this bug. It may not deserve being in iteration 3.

**Comment by f1ames** [comment]
I checked on https://ckeditor5.github.io (v0.7.0) and current dev and I am unable to reproduce this issue in Safari 10.0.1.

**Comment by Reinmar** [comment]
I'm not able to reproduce this as well. I tried maany variations but all worked fine.
