### ISSUE TITLE
Removing word also removes the preceding space

### ISSUE THREAD

**Issue by prebenlm** [ckeditor/ckeditor5-typing#30]
Not sure if this is the correct project or if you even want bugs yet submitted by normal people. If I shouldn't have reported this, I'm sorry. 

Tested here: https://ckeditor5.github.io/

**Steps to reproduce:**
- Write "Hello world"
- Remove "world". Either by selecting it and backspace or simply backspace each character

**What happens:**
The word "world" is removed. However, the space that was between "Hello" and "world" is also removed. 

**Expected result**
For the word "world" to be removed, but not the space. If the behavior above is intended, then that behavior is unexpected for me at least. 

Tested with latest Chrome browser (52.0.2743.82) on Mac OS X.

**Comment by scofalik** [comment]
Hello and thank you for your contribution. We welcome community feedback at any stage of the project!

The best place to report bugs of unknown origin would probably be https://github.com/ckeditor/ckeditor5. This bug looks like bug with typing, but it is actually connected with rendering. As you can see in HTML inspector, or by executing `editor.document.getRoot().getChild( 0 ).getText()`, the space is still there, but it should be converted to `&nbsp;` to be correctly rendered.

There are many bugs in CKEditor5 0.1.0 version that we know about and this is one of them, though I can't find right now this exact case described. Here is an issue that fits best: https://github.com/ckeditor/ckeditor5-engine/issues/379. I will submit your case there.

As you can see in linked issue, it is set to be done in milestone `iteration 3`, which is the next milestone after the current one (that we are slowly closing). If you find it interesting, here are other tickets set for `iteration 3` which is mostly about fixing known bugs and bringing in browser support: https://github.com/ckeditor/ckeditor5-engine/milestone/3.

Feel free to report any other bugs you might find in CKE5 v.0.1.0, however keep in mind that the version is intended to showcase the new editor architecture and we will be intensively working on fixing bugs in very near future.
