### ISSUE TITLE
Caret is moved to the end of the paragraph when typing a letter at the end of a link

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-typing#47]
![sep-22-2016 13-49-30](https://cloud.githubusercontent.com/assets/156149/18747226/66761dc6-80cc-11e6-99b5-374b5dea0947.gif)

(No error is thrown.)

May be related to https://github.com/ckeditor/ckeditor5-typing/issues/39#issuecomment-240416142.

**Comment by pomek** [comment]
I was trying to resolve this issue, but it is a little bit more complicated than I suppose.

Basically, the issue as such as is now isn't longer valid. You cannot add any letter at the end of a link. 

I tried to append any letter at the end of bold. It works proper but [I noticed that I have an infinite loop in the code](https://github.com/ckeditor/ckeditor5-engine/issues/590#issuecomment-250435708).

Unfortunately, most probably the above ticket has to be done before it.
