### ISSUE TITLE
Handle &nbsp; inserted by browser instead of spaces.

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-typing#49]
When typing, browsers insert `&nbsp;` char whenever it is needed to correctly display inserted space. Since we decided that we want to keep view and model clean, we don't want those `&nbsp;`s. This means, that we need to get clean them.

**Comment by fredck** [comment]
> When typing, browsers insert &nbsp; char whenever it is needed to correctly display inserted space.

Are you talking about sequences of spaces? If so, it may not be in the model, but it's certainly a requirement in the view.

**Comment by Reinmar** [comment]
It's definitely not a requirement in the view. The view format independent. Subsequent spaces may be differently rendered depending on a data format, so it DP's role to render them as it wishes.
