### ISSUE TITLE
Implement ChangeBuffer

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-typing#5]
Typing and backspace need to group changes into batches to create bigger undo steps (one batch means one undo step). This mechanism must count atomic changes and return new batch every time some limit was exceeded. Additionally, it must watch other changes applied to the document, because every time a new batch appears, `ChangeBuffer` should be cleared as well (so e.g. characters typed after inserting an image are not undone together with characters typed before).

**Comment by Reinmar** [comment]
> because every time a new batch appears, ChangeBuffer should be cleared as well

This bit is tricky. Figuring out whether a new change comes with a new batch can be done in two ways:

* By remembering all previous batches in a weak set.
* By checking baseVersion.

**Comment by Reinmar** [comment]
After a long discussion we decided that this can be done by checking whether batch has just one operation. This will be the easiest way, however, we'll need to ensure in the engine that operations are applied to the document right after the delta is added to the batch (or something like that – @pjasiun will clarify that :D).

**Comment by pjasiun** [comment]
https://github.com/ckeditor/ckeditor5-engine/issues/386
