### ISSUE TITLE
[FF] Cannot type space at the end of paragraph

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-typing#52]
We spent a while investigating that and it turns out that there are 4 mutations generated by Firefox and they are a bit weird. They confuse `MutationObserver` which doesn't fire an event for the text change.

It'd be worth to check this scenario on bare contenteditable and report a bug to Firefox team if we're right that the mutations make no sense.

**Comment by f1ames** [comment]
In Firefox there is one additional mutation. In other browsers it looks like:

```
1.
oldValue: " instance."
type: "characterData"
2.
oldValue: " instance. "
type: "characterData"
3.
oldValue: " instance."
type: "characterData"
```

While in Firefox it looks like:

```
1.
oldValue: " instance."
type: "characterData"
2.
addedNode: "<br>"
type: "childList"
3.
oldValue: " instance. "
type: "characterData"
4.
oldValue: " instance.  "
type: "characterData"
```

So there are two differences:
- double space in last mutation `oldValue` text (not a problem)
- additional mutation inserting `<br>` (cause of this issue)

The second cause is the fact that all text mutations are inside a text node which is a child of mutated element and are not processed by mutation observer (https://github.com/ckeditor/ckeditor5-engine/blob/t/460/src/view/observer/mutationobserver.js#L163).

**Comment by f1ames** [comment]
There are two issues here:
- The mutation observer generates `childList` mutation which is not properly handled (it is skipped) by `Input` module.
- The only changed child in generated mutation is newly added `br` element. Even if the mutation will be properly handled and rerendered the space still won't be there.

> It'd be worth to check this scenario on bare contenteditable and report a bug to Firefox team if we're right that the mutations make no sense.

It works same way in bare contenteditable. However, having in mind that Firefox inserts the `br` in such case (in bare cE) I think the mutations should be considered valid.

**Comment by Reinmar** [comment]
But why is that `<br>` insertion (which we're going to revert anyway) causing any issues? What the typing feature needs to catch is the insertion of the space – the text node value change. Why doesn't it catch it?

**Comment by f1ames** [comment]
> But why is that `<br>` insertion (which we're going to revert anyway) causing any issues? What the typing feature needs to catch is the insertion of the space – the text node value change. Why doesn't it catch it?

Because of the way the mutation observer handles DOM mutations in this case. The modified text has the same parent as inserted `br` so [characterData mutations are skipped](https://github.com/ckeditor/ckeditor5-engine/blob/master/src/view/observer/mutationobserver.js#L163) and the mutation of type `children` is fired by the observer. Which is no processed by typing feature as you mentioned, because it [is not a text change](https://github.com/ckeditor/ckeditor5-typing/blob/master/src/input.js#L228).

Seems like a FF specific issue, should we look for a specific fix for this or a more generic approach?

**Comment by Reinmar** [comment]
If mutation observer needs to work this way (skip text mutations if other children changed), then we'll need a targetted fix for this. The typing feature will need to listen for that particular (with some dose of strictness) mutations set and handle it.

cc @pjasiun

**Comment by pjasiun** [comment]
The role of the `view.MutationObserver` it to filter out redundant mutations, so plugins which observe it has a (more-less) clear event. Also, the general role of view observers is to hide differences between browsers, so it is clear that `view.MutationObserver` should handle it and fire the proper event.

Now. We can a lot of "characterData" mutation in a case of operations like "break" paragraph and we do not want to handle then by the typing feature. This is why we do not fire "characterData" mutation if parent child list change, assuming that the change will be handled as a change of child's list. 

In this case, I agree that we need a dedicated solution for Firefox ugly mutation, so to handle bogus `<br>`s in a special way. `view.MutationObserver` seems to be a good place to hide all of the ugly code.

**Comment by Reinmar** [comment]
> In this case, I agree that we need a dedicated solution for Firefox ugly mutation, so to handle bogus <br>s in a special way. view.MutationObserver seems to be a good place to hide all of the ugly code.

I'm not 100% sure about this. It may happen that MO will need to know a lot about those <br> insertions to actually know which of these mutations filter out.

OTOH, it would be great if we'd be able to hide this in a MO. It has the biggest knowledge about the mutations so it can easily filter out the `<br>` insertion mutation and I guess the rest would just work out perfectly.

So, if we want to go this way – I'll try with something like:

1. Check the list of native mutations for `<br>` element insertion. If that insertion was at the end of an element (we could check what element is it... but let's KISS for now), just remove it from that list of mutations.
2. Do the rest normally.

I don't know how MO works in details, but perhaps after doing 1. the 2. will just do fine.

**Comment by pjasiun** [comment]
> I'm not 100% sure about this. It may happen that MO will need to know a lot about those 
> insertions to actually know which of these mutations filter out.

If we will go this way we will create a mutation event as messy as the original one. We may add addition informations later if we find them usefull, but let's try to keep this event as simple to use as possiblem.

> So, if we want to go this way – I'll try with something like:
> 
> Check the list of native mutations for <br> element insertion. If that insertion was at the end of an element (we could check what element is it... but let's KISS for now), just remove it from that list of mutations.
> Do the rest normally.

:+1:
