### ISSUE TITLE
Tab deletes text – add tab to safeKeycodes

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-typing#69]
TC:

1. Open editor.
2. Select some text.
3. Press tab.

Text is deleted.

**Comment by f1ames** [comment]
I noticed there are only some non-printable keys covered in unit test - [tests/input.js#L303](https://github.com/ckeditor/ckeditor5-typing/blob/master/tests/input.js#L303). Maybe it will be good to cover all keys. Having covered only some keys is sufficient in situation when something directly inside safe keycodes handling breaks. In future there might be other functionalities impacting only some of safe key codes (which are not covered in tests), WDYT?

**Comment by Reinmar** [comment]
We can cover all the keys by the tests, but having 1:1 situation doesn't mean that we're safe. As we can see in this issue, the problem was that we forgot about one of the keys rather that one of them wasn't handled correctly due to some conflicts.

Please note that this feature is tested nearly separately, independently of the other features. This means that this test won't catch conflicts between features anyway. For that, we'd need an integration tests, and we're not doing a lot of those yet.

I hope I understood your comment correctly :) If not, then let me know.

**Comment by f1ames** [comment]
@Reinmar Everything clear, integration tests will better cover the cases I was think of, so that is a way to go as you suggested.
