### ISSUE TITLE
ChangeBuffer: undo changes should reset the buffer

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-typing#7]
Currently, the undone and redone changes are applied without batch. We planed to handle collaborative changes in the same way (without batches). However, typing needs to handle both types differently, because undo should reset the buffer, while collaboration should not. We'll need batch type most likely (see ckeditor/ckeditor5-engine#443).

**Comment by scofalik** [comment]
https://github.com/ckeditor/ckeditor5-engine/pull/499 Will introduce batch types and this feature should skip all batch with `transparent` type.
