### ISSUE TITLE
[FF] Unable to delete text inside of word corrected by native spellchecking.

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5-typing#73]
1. Go to http://localhost:8125/ckeditor5-typing/tests/manual/input.html
2. Type `comuter` in `This is an editor instance.`, like `This is comuter an editor instance.`
3. Right click on `comuter` and correct it to `computer` from context menu.
4. Move caret inside e.g. `comp^uter`.
5. Press backspace.

**Expected:** `p` gets deleted.

**Actual:** Caret is moved to the end of the word `computer^` and `r` gets deleted.

It is related to #3 (or should be a subtask of #3).

**Comment by Reinmar** [comment]
I can't reproduce it. WFM on FF 52.0b8. But, did you enable selectionchange event in FF? I never remember how to do that... here you have some hints: https://github.com/ckeditor/ckeditor5-engine/issues/407

**Comment by f1ames** [comment]
Yes, it was caused by not enabling `onselectionchange` event in FF.
To enable it `about:config` -> `dom.select_events.enabled`.
