### ISSUE TITLE
[Chrome, Android] Unable to delete some parts of the text in the last line.

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5-typing#75]
1. Go to http://localhost:8125/ckeditor5-typing/tests/manual/spellchecking.html (available on `t/3`).
1. Place selection at the end of the last line: `The new <strong>co</strong>mu<em>ter</em>.[]`
1. Press backspace.
    - Period on the end is skipped instead of being deleted: `The new <strong>co</strong>mu<em>ter</em>[].`
1. Press backspace 3 more times: `The new <strong>co</strong>mu[]`
1. Press backspace few more times.
    - Nothing happens, the content before selection is not deleted.

I also checked the issue on the phone with newer Android (version 6 instead of 4), but with the same up-to-date Chrome version. The behavior was a little different and pressing backspace on the end of the content **(2.)** just does nothing.

**Comment by Reinmar** [comment]
This was my worry for a long time. My guess here is that the lack of `keyCode` in the `keydown` event on Android means that our normal `event => command` handler doesn't work.

Most of the time, when deleting text, the mutation observer will handle it. But not in the case you mentioned, because the `'.'` text node gets deleted, which is not common for typing (for which we use the mutation observer) so the change was rejected.

We'll need to check whether the `keydown` event finally provides some other data based on which we could trigger the command. If not, we'll need to improve the mutation observers.

**Comment by Reinmar** [comment]
I've checked what `keydown` brings on Android:

![image](https://user-images.githubusercontent.com/156149/27580766-fd9dab6c-5b2b-11e7-8d72-8931a5a825ae.png)

This is a log for: <kbd>A</kbd>, <kbd>Space</kbd>, <kbd>Enter</kbd>, <kbd>Backspace</kbd>.

Only <kbd>Enter</kbd> brings any information. This means that for <kbd>Backspace</kbd> (which is the biggest problem here) we need to either try using unstable and unspeced `beforeinput` (if it's available still) or some really smart heuristic.

Besides, we need to consider this case in `isSafeKeystroke()`.

**Comment by f1ames** [comment]
Checked on Chrome `67` on `Android 8` and the cause seems to be a little bit different. When the content is already formatted like `The new <strong>co</strong>mu<em>ter</em>.[]`, _backspacing_ works fine, so I wasn't able to reproduce this issue any longer in a way it is described.

However, if you try to create such content, when placing `.` after turning off inline style the `Uncaught CKEditorError: view-renderer-filler-was-lost: The inline filler node was lost.` error is thrown. So **placing `.` on the end of the line after turning off inline style throws an error**:

![android typing 1](https://user-images.githubusercontent.com/1061942/41839187-d4c96a82-7862-11e8-8021-e856247708cd.gif)

The error is caused by the fact that typing `.` triggers autocorrection mechanism which causes an issues on the end of the line. In the middle of the text it works fine:

![android typing 2](https://user-images.githubusercontent.com/1061942/41839409-7920ac6c-7863-11e8-9c08-6f90bbb2f9f7.gif)

Apart from the fact that text losses its styling.

I'm extracting those two cases to separate issues.
