### ISSUE TITLE
[Safari] Cannot type space after misspelled partially styled word.

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5-typing#76]
Extracted from #3, should be checked while working on #74.

Autocorrect in Safari corrects misspelled words after typing space. While at the moment editor ignores corrections for partially styled words, space is also not inserted. So basically typing space after misspelled word (which was marked by the spellchecker) is not possible.

**Comment by Reinmar** [comment]
Still buggy?

**Comment by f1ames** [comment]
I will take a look on it soon.

**Comment by f1ames** [comment]
Looks like it was fixed 🎉 

![safari1](https://user-images.githubusercontent.com/1061942/38426711-b0a01f46-39b7-11e8-8e40-5d441e9446ee.gif)
