### ISSUE TITLE
[FF] Word on the end of the paragraph is not corrected by spellchecking.

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5-typing#77]
1. Open the editor, (e.g. https://ckeditor5.github.io/).
1. Remove whole content and paste `The comppputer`.
1. Try to correct word `comppputer` to `computer` using native spellchecking.

Nothing is inserted and word is not corrected.

For this case, FF generates mutations with `type: children` (some of them) and the mutation produced by `MutationObserver` is also of this type. The number of changes is greater than 1 so the code [exits here](https://github.com/ckeditor/ckeditor5-typing/blob/eee3c80d4cac8c96270608548c0f0975973be63b/src/input.js#L245) without applying any changes.

**Comment by f1ames** [comment]
Actually, the array of 7 mutations is generated by the browser for this case and only one is of `type: children`. This one mutations adds `<br>` element which is a FF specific behavior.

**Comment by f1ames** [comment]
I think this is the same cause as in #52.

**Comment by Reinmar** [comment]
I can't reproduce this on https://ckeditor5.github.io, neither on master (after https://github.com/ckeditor/ckeditor5-engine/issues/882).

**Comment by f1ames** [comment]
@Reinmar - strange, have you tried with Firefox (my version 52.0.1). Seems to be still reproducible on https://ckeditor5.github.io/.
![mar-23-2017 09-37-23](https://cloud.githubusercontent.com/assets/1061942/24238980/6ad354a0-0fac-11e7-8b95-89654b6a1389.gif)

**Comment by pomek** [comment]
I also can reproduce this issue.

**Comment by Reinmar** [comment]
I'm using 53.0b5 (64-bit). In any case – it's fixed on t/52, right? :)

**Comment by f1ames** [comment]
Yes, it was the same cause as #52.
