### ISSUE TITLE
[Chrome][Safari][IME] Starting composition on non-collapsed selection containing partially styled element throws an error.

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5-typing#83]
1. Go to http://localhost:8125/ckeditor5-typing/tests/manual/input.html.
2. Select `<p><em>Th[is</em> is] an <strong>editor</strong> instance.</p>`.
3. Start the composition (_Spanish-ISO_ with `'` or _Hiragana_ with e.g. `a`).

**Chrome**
The character starting the composition is inserted (marked as `X` below), but the resulting html is
`<p><em>ThX[]</em>] is an <strong>editor</strong> instance.</p>`, which means only styled part of the selection was replaced. Also an error is throw `Uncaught TypeError: Cannot read property 'parent' of null`.

**Safari**
Resulting html is `<p><em>ThX[]s</em>] an <strong>editor</strong> instance.</p>`, no error thrown.

**Comment by f1ames** [comment]
Works fine on FF. On Chrome still behaves as described above. Safari seems to replace selection properly (resulting in `<p><em>ThX[]</em>] an <strong>editor</strong> instance.</p>`), however composition does not start.

**Comment by f1ames** [comment]
Rechecked with https://github.com/ckeditor/ckeditor5-engine/issues/1417, still reproducible as described in the above comment.

**Comment by Reinmar** [comment]
Do I understand correctly that `_handleKeydown()` doesn't work in this case? That's bad... It exactly the thing that was supposed to prepare the DOM for upcoming composition.

**Comment by f1ames** [comment]
> Do I understand correctly that _handleKeydown() doesn't work in this case? That's bad... It exactly the thing that was supposed to prepare the DOM for upcoming composition.

Well, it looks like. I mean, it does nothing because selection is collapsed in this case. So if it was the assumption that it will "remove" selection contents before composition is started then yes, it does not work. I wonder why selection is collapsed in this case, looking at events order, **keydown** should be handled first so selection still should be not affected by any composition mechanisms 🤔 

![image](https://user-images.githubusercontent.com/1061942/40987422-c3b43f94-68e8-11e8-821f-670238bc9f54.png)

**Comment by Reinmar** [comment]
It's worth reporting upstream. But we'll need to figure something out too. The idea was that we don't want to allow character insertion on a non collapsed selection because this may lead to a lot more mutations that we're able to handle. E.g. when blocks merge it's a disaster for us. Therefore, it would be great if there was some way to handle this also when composition starts. Can we do that on compositionstart itself? I guess not - because our DOM changes will break composition. So is there any other event?

**Comment by f1ames** [comment]
This behaviour is somehow strange. I prepared [a codepen](https://codepen.io/f1ames/pen/ZROaVx?editors=1010) to check on what events selection is still non-collapse. For regular typing and composition I get very similar results. For regular typing (boolean value after event type shows if selection is collapsed):

![image](https://user-images.githubusercontent.com/1061942/41029824-02a52440-697d-11e8-81ed-94770af1852f.png)

and for Spanish accent:

![image](https://user-images.githubusercontent.com/1061942/41029878-32170838-697d-11e8-9aca-bfc77b6482fb.png)

which means in our `keydown handler` selection should still be non-collapsed one. However, I also noticed strange behaviour while debugging:

![ime strange](https://user-images.githubusercontent.com/1061942/41030212-176254e2-697e-11e8-98d5-a344417572eb.gif)

So at least one of this things deserves an upstream.

**Comment by f1ames** [comment]
Ok, the cause is slightly different here 😬

Since while debugging the selection seems to be collapsed (because of some strange behaviour shown in the comment above) I thought this is the case here. However, when using good ol' `console.log` I can see selection is not collapsed. The code exists because of [`isSafeKeystroke( evtData )` call](https://github.com/ckeditor/ckeditor5-typing/blob/274fb704a683588871e1d401eadeb478a3c237dc/src/input.js#L84).

So `229` key code (which means composition start/end) is treated as `safe keystroke` here and that's the problem. I'm not sure what was the reason for it and if we could change that. Btw. I did a super quick test and removing `229` from `safe keystrokes` helps in this case, but it will break every case when selection is non-collapsed during composition / on composition end (e.g. Japanese Hiragana) as it will remove newly composed sequence 😞

**Comment by Reinmar** [comment]
Try `git blame`. I think we added this at some point... Perhaps even you did that :D

**Comment by f1ames** [comment]
> Try git blame. I think we added this at some point... Perhaps even you did that :D

Yes, indeed 😅 One of the reasons is what I mentioned in a previous comment probably:

> ... it will break every case when selection is non-collapsed on composition end (e.g. Japanese Hiragana) as it will remove newly composed sequence (because you confirm composition with key press like <kbd>Enter</kbd>) 😞

So I think the potential fix can work like:

* If not during composition `229` key code should also trigger content deletion in a `_handleKeydown()`.
* If during composition `229` key code should not trigger content deletion in a `_handleKeydown()`.

From what I see (at least for Hiragana) `compositionend` event is fired after `keydown` so it may work like that. But it's just a quick idea and should be investigated further - but seems like a good place to start.

**Comment by f1ames** [comment]
So I went with the approach mentioned in the https://github.com/ckeditor/ckeditor5-typing/issues/83#issuecomment-395027323 above and it has some potential. I have implemented the fix and tested it on Chrome, Firefox and Safari with macOS accent panel, Spanish, Japanese (Hiragana) and Korean (2-Set) keyboards.

It works fine on Chrome (which means fixes the issue) and Firefox. However, there are some issues on Safari - the order of events is different in some cases:

* `keydown` is fired after `compositionend` so it removes inserted characters (happens especially for macOS accent panel).
* `keydown` is fired after `compositionstart` so its handler would not remove selected content (for Spanish, Japanese and Korean).

![safari test1](https://user-images.githubusercontent.com/1061942/41298503-ccd5f76a-6e61-11e8-9635-9043bef99d01.gif)

---

I think for Safari we may try one more think in the `keydown` handler. If `keydown` with `229` key code is fired during composition it should additionally check if there is non-collapsed selection which spans over more than one element.
For other browser there will be only collapsed selection as initial fix covers it. If something was already composed, the selection is non-collapsed but it contains text only. So the above check will be triggered only for Safari cases. The only important think is to make sure if DOM manipulation in such state of composition doesn't break it.

**Comment by f1ames** [comment]
> The only important think is to make sure if DOM manipulation in such state of composition doesn't break it.

Checked and it removes also a character which started a composition 🤔

**Comment by f1ames** [comment]
So the final solution I came up with works as follows:

* If there is a `keydown` with 229 `code` outside composition, selection content is removed.
* If there is a `keydown` with 229 `code` during composition, selection content is not touched.

This covers Chrome where events order is `keydown:229`, `compositionstart`, `keydown:229`, `compositionend`.

However, on Safari the order in most cases is `compositionstart`, `keydown:229`, `compositionend`, `keydown:229`. The above solution will not work and break the composition so additional checks were needed:

* If on `compositionstart` there is non-collpased, not flat selection it means `keydown` handler didn't kick-in so selection content is removed (and it works well and does not break the composition) - this covers composition starting sequence `compositionstart`, `keydown:229`.
* If there is a `keydown` with 229 `code` outside composition, but the selection is the same as upon ending composition (`compositionend` event), selection content is not removed (otherwise composed sequence will be removed) - this covers composition ending sequence `keydown:229`, `compositionend`.

**Comment by f1ames** [comment]
There is an issue in Edge browser. Composition there works slightly different:

* Spanish accent does not fire `composition` events at all, but `_handleKeydown()` work well in this case.
* Composing Korean works as in Safari (`compositionstart`, `keydown`) so `compositionstart` handler takes care of it. 
* Composing Japanese (Hiragana) works as in Chrome (`keydown`, `compositionstart`), however removing content on `keydown` results in composed character not showing. It seems that it may be caused byt the fact that content removal changes the selection so composed character does not appear 🤔 

---

I also noticed one  issue on Chrome caused by the current implementation. When starting Japanese composition (only native macOS IME keyborad, works fine with Google ones) over non-collapsed selection, you have to then press `left/right arrow` because navigating through IME panel after starting composition with `up/down arrow` keys is not possible.

![chrome ime](https://user-images.githubusercontent.com/1061942/41712137-171eb3ae-754a-11e8-861d-0d2d8632a0c3.gif)

**Comment by f1ames** [comment]
So the above problem with Chrome is caused by the fact that whole text nodes gets replaced in the `renderer._updateChildren()` method (see https://github.com/ckeditor/ckeditor5-engine/issues/1425 issue which is exactly about this). Text node gets replaced and then selection is put inside a new text node which apparently disturbs the composition flow.

I did a fast check and fixing https://github.com/ckeditor/ckeditor5-engine/issues/1425 seems to help.

**Comment by f1ames** [comment]
I did a test on plain `contenteditable` on Edge to see if removing selection contents on `keydown` breaks the composition as described above and it does (https://codepen.io/f1ames/pen/vrRqba?editors=1010).

This is not identical behaviour to what happens in the editor (content is not removed directly, changes are passes through a model and then are rendered), but the end result is the same so it seems this is more native behaviour (I also checked it with quick-fix for ckeditor/ckeditor5-engine#1425 mentioned in the comment above, but it doesn't change anything).

**Comment by f1ames** [comment]
Some thoughts not directly connected with this issue, but more with a fix and how things works. W3 documentation describes `compositionstart` event and in particular:

> When a keyboard is used to feed an input method editor, this event type is generated after a `keydown` event, but speech or handwriting recognition systems MAY send this event type without keyboard events.

So clearing composition contents on `keydown` may not work in some mentioned cases (_speech or handwriting recognition systems_), but these are really edge cases so we may get back to it when needed.

**Comment by f1ames** [comment]
I have reported the Edge issue https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/17997826/. ATM I'm not sure if it will be fixed by the browser vendor, because I haven't found a part describing this specific behaviour in any W3 specs, which may mean it is not an incorrect behaviour. Still, it works different/better in other browsers so I gave it a try.
