### ISSUE TITLE
[Safari][IME] MacOS balloon accent composition breaks on the end of inline styled elements after using arrow keys.

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5-typing#87]
1. Go to http://localhost:8125/ckeditor5-typing/tests/manual/input.html.
2. Set selection like `<em>This[]</em> is an <strong>editor</strong> instance.`.
3. Open MacOS accent balloon (e.g. long <kbd>a</kbd> press).
4. Try to navigate with arrow keys.

After navigating with left/right arrow keys the accent is inserted and composition ends. Most likely it is related to the fact that selection is updated during navigation, however the cause of selection change is different than in #86.

**Comment by Reinmar** [comment]
Yet another story for the book of why not to render when composition takes place.

Apparently we try to re-render the selection which breaks the composition. It also affects Chrome where we can see that selectionchange-infinite-loop is thrown which means that we try to place the selection in a place where the browser doesn't want it to be.

**Comment by Reinmar** [comment]
This is a quite important issue because it will break everytime someone tries to use that long-press when typing at the end of an inline style.

It wouldn't critical, though, because it's not that popular feature, but we checked that it also breaks composition for Hiragana. So it is very important.

**Comment by f1ames** [comment]
The cause of this issue is the fact that renderer treats selection like
`<p><em>Text1{ą}</em></p>`
and
`<p><em>Text1{ą</em>]</p>`
as two different selections and rerenders it during composition. This breaks composition in Safari and causes loop in Chrome (when you navigate through accents with arrow keys fast).

**Comment by Reinmar** [comment]
So, as we discussed – there are two options:

* disable rendering selection when compositon takes place (should be fairly simple),
* try to change the renderer so it doesn't touch the selection if it's "similar" to the expected one.

The latter is really tricky but we should do it one day anyway, also for some other reasons (the fact that SelectionObserver doesn't call `render()` now is, according to @pjasiun, a bug). The former is much simpler a can be a quick win now, so IMO it's worth checking. I would propose to not touch the second option for now.

**Comment by pjasiun** [comment]
I'm for option 2, because it's not only a composition what is the problem when we render selection in such cases, for instance creating selection by Ctrl+mouse an issue too.

BTW, here is a ticket about calling `render()` in `SelectionObserver`, @Reinmar mentioned: https://github.com/ckeditor/ckeditor5-engine/issues/796

**Comment by f1ames** [comment]
Created an issue for this https://github.com/ckeditor/ckeditor5-engine/issues/887.

**Comment by f1ames** [comment]
Checked on Safari (11.0.3 (11604.5.6.1.1), and also Chrome and FF) and it works fine so I'm closing this issue.
