### ISSUE TITLE
Ctrl + backspace doesn't delete the entire word

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-typing#92]
Reported in https://github.com/ckeditor/ckeditor5/issues/414.

**Comment by fredck** [comment]
After a quick test, it seems that browsers support word deletion using word boundaries common to the English language, with no special support for other languages.

For example, when pasting Japanese text, which doesn't use spaces between words, the whole **line** of text is deleted.

In fact, the only special behavior is that it deletes line by line, not the whole text.

**Comment by Reinmar** [comment]
Check this:

ພາສາຈີນແມ່ນພາສາໜຶ່ງທີ່ເວົ້າໃນປະເທດຈີນ.

And this:

にほんごの クラスは かようびと もくようびです。

In my case, alt+backspace deletes bigger pieces of this text, but definitely not whole lines. Ctrl+backspace works like backspace.

So, first of all, at least on macOS, alt+backspace means "delete word". I don't think that Ctrl+backspace has some special meaning. How's it on Windows?.

Second of all, it's really not that simple.

**Comment by Reinmar** [comment]
DUP reported in https://github.com/ckeditor/ckeditor5/issues/501.

**Comment by fredck** [comment]
I'm fine if we bring support for western languages first, before thinking to come with the perfect solution for all languages.

**Comment by Reinmar** [comment]
Turns out that this gets heavily irritating for people who got used to this keystroke (e.g. to fix up typos).

So, a temporary solution could be to discover ctrl+backspace (windows) or alt+backspace (macos) and delete the entire word by looking back to the previous space (`foo bar^` => `foo ^`).

However, it seems that we'll need to start depending on mutations for this to work reliably anyway. There are two problems with handling backspace manually – Android (where there's no key code for backspace) and languages where "word" has a different shape in the text. Also, there may be other kinds of keystrokes like "delete the whole line" and by handling mutations we'd handle them too. This is a bigger task though due to all the tiny little details like diff failing on comparing "xxx^" with "xx^", combined characters, IME (where selection isn't collapsed) etc, etc. But all these things are also the reason to actually use mutations :)

**Comment by ryanfeeley** [comment]
Will be glad to see this live, lots of requests for it in Firefox Notes.

**Comment by jodator** [comment]
> So, a temporary solution could be to discover ctrl+backspace (windows) or alt+backspace (macos) and delete the entire word by looking back to the previous space (foo bar^ => foo ^).

This is actually partially supported by `Delete` plugin:

https://github.com/ckeditor/ckeditor5-typing/blob/9b55a32202084ca310e4c56f6f87e6a677a099a5/src/delete.js#L36-L40

The problems in my opinion lays here:
https://github.com/ckeditor/ckeditor5-engine/blob/adf1043096b4042e1f0240a0c3553addbe1773e7/src/model/utils/modifyselection.js#L120

As it appears that `modifySelection()` does not support `unit=word` option - the tests are only for `character` or `codePoint`:
https://github.com/ckeditor/ckeditor5-engine/blob/1640a51447d14acf3a961a5d316f6dc0c2e65d83/tests/model/utils/modifyselection.js#L25-L26.

I'll try to dig more into it and to implement `unit=word` handling there.

**Comment by Reinmar** [comment]
> As it appears that modifySelection() does not support unit=word option - the tests are only for character or codePoint:

Yep. We predicted this thing but never fully implemented it.

**Comment by jodator** [comment]
@Reinmar how broad should we go with implementing this?

A space only solution is I understand a minimal solution but maybe we should add other punctuation symbols (`,.-`)?

As a reference here is [Unicode Word Boundary specification](https://www.unicode.org/reports/tr29/#Default_Word_Boundaries).

**Comment by Reinmar** [comment]
Max 3MH broad ;)

**Comment by Reinmar** [comment]
Closed with https://github.com/ckeditor/ckeditor5-engine/pull/1287. Great job!

**Comment by jodator** [comment]
To have everything right in papers - I'm reopening this as there is still a PR awaiting in this repository which will enable `Ctrl+Backspace` to work also on non-mac computers :).
