### ISSUE TITLE
Missing editor destroy in some of tests

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-typing#98]
This causes https://github.com/ckeditor/ckeditor5-engine/issues/937 what's kinda weird.

**Comment by oskarwrobel** [comment]
https://github.com/ckeditor/ckeditor5-engine/issues/937 is not the only problem. 

Running engine tests right after typing fails one test case.
```
gulp test --files typing,engine
```
```
FAILED TESTS:
  EditingController
    conversion
      ✖ should convert selection from view to model
        Chrome 58.0.3029 (Mac OS X 10.12.4)
      Error: Uncaught AssertionError: expected '<paragraph>[]foo</paragraph><paragraph></paragraph><paragraph>bar</paragraph>' to equal '<paragraph>foo</paragraph><paragraph></paragraph><paragraph>b[a]r</paragraph>' (node_modules/chai/chai.js:206)
```

There might be more similar situations but "luckily" typing is at the end of the repositories list and typing tests are run as one of last.

**Comment by Reinmar** [comment]
Does your PR help with that?

**Comment by oskarwrobel** [comment]
Yes.
